# -*- coding: utf-8 -*-
"""DEV_Assignment(21AIA05).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X7GP8f_YYipFmkfr_m18iY0hbFRYndqI
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("passengers.csv")

th=df.head(1000)

hd=th.head(100)

hd.head()

hd.tail()

hd.describe()

hd.info()

hd.shape

hd.columns

hd.nunique()

hd["airlineid"].unique

hd.isnull().sum()

x=th.usg_wac
y=th.fg_wac
a=hd.usg_wac
b=hd.fg_wac
plt.scatter(x,y)
plt.xlabel('usg_wac')
plt.ylabel('fg_wac')
plt.show

hd.plot()

plt.plot(a,b)
plt.show

hd.plot(kind='bar')

hd.plot.barh()

hd.plot.bar(stacked=True)

plt.bar(a,b, label="red Bar" ,color='r')
plt.xlabel("usg_wac")
plt.ylabel("fg_wac")
plt.title("International Report Passengers")
plt.legend()
plt.show

hd.Month.hist(bins=20)

plt.hist(a)
plt.show

df=pd.DataFrame(np.random.randn(10,2),columns=['usg_wac','fg_wac'])
df.plot.box()

hd.plot.area()

plt.stem(a)
plt.show

plt.pie(a)
plt.show

plt.polar(a)
plt.show